apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - realm-import.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: iam
      app.kubernetes.io/part-of: governance
