apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: vault
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  type: ClusterIP
